import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {bossRules,bossResult,answerReward,shieldTier,resetTestMode,reducedMotionCss,developerCodeValid,fiveTapUnlocked,exportWithoutTest,cosmeticPurchase} from '../scripts/progression-rules.mjs';

const app=()=>fs.readFileSync(new URL('../src/app.ts',import.meta.url),'utf8');

test('boss rules match v3.1 specification',()=>assert.deepEqual(bossRules,{unit:{questions:5,threshold:70,reward:10},objective:{questions:8,threshold:75,reward:25},domain:{questions:12,threshold:80,reward:75},final:{questions:15,threshold:85,reward:150}}));
test('one question cannot defeat a boss',()=>{const r=bossResult('unit',1,1,false);assert.equal(r.complete,false);assert.equal(r.passed,false);assert.equal(r.reward,0)});
test('full battle completion and threshold are required',()=>{assert.equal(bossResult('unit',4,4,false).passed,false);assert.equal(bossResult('unit',3,5,false).passed,false);assert.equal(bossResult('unit',4,5,false).passed,true)});
test('boss rewards issue once',()=>{assert.equal(bossResult('final',13,15,false).reward,150);assert.equal(bossResult('final',13,15,true).reward,0)});
test('normal reward baseline is restrained and idempotent',()=>{assert.deepEqual(answerReward({correct:true,firstAttempt:true,confident:true}),{xp:2,coins:0,testCoins:0});assert.deepEqual(answerReward({correct:true,firstAttempt:false,confident:false}),{xp:1,coins:0,testCoins:0});assert.equal(answerReward({correct:true,previousStage:'introduced',newStage:'understood',alreadyRewarded:false}).coins,2);assert.equal(answerReward({correct:true,previousStage:'introduced',newStage:'understood',alreadyRewarded:true}).coins,0)});
test('shield thresholds require substantial real evidence',()=>{assert.equal(shieldTier({understood:10,applied:0,retained:0,unitBosses:0,objectiveBosses:0,domainBosses:0,examReady:0,readiness:0,finalBoss:false}),'Basic');assert.equal(shieldTier({understood:10,applied:0,retained:0,unitBosses:1,objectiveBosses:0,domainBosses:0,examReady:0,readiness:0,finalBoss:false}),'Bronze');assert.equal(shieldTier({understood:300,applied:150,retained:75,unitBosses:8,objectiveBosses:3,domainBosses:2,examReady:0,readiness:60,finalBoss:false}),'Platinum');assert.equal(shieldTier({understood:500,applied:400,retained:400,unitBosses:20,objectiveBosses:10,domainBosses:5,examReady:300,readiness:85,finalBoss:true}),'Security+ Master')});
test('test mode leaves real state unchanged and resets separately',()=>{const real={xp:100,coins:12,mastery:55};const out=resetTestMode(real,{enabled:true,coins:999,unlockedCosmetics:['all']});assert.deepEqual(out.real,real);assert.equal(out.test.coins,0);assert.deepEqual(out.test.unlockedCosmetics,[])});
test('test mode is excluded from export',()=>{const out=exportWithoutTest({xp:10,testMode:{enabled:true,coins:10000,unlockedCosmetics:['all']}});assert.equal(out.xp,10);assert.equal(out.testMode.enabled,false);assert.equal(out.testMode.coins,0);assert.deepEqual(out.testMode.unlockedCosmetics,[])});
test('cosmetic purchase cannot affect learning progress',()=>{const real={readiness:72,mastery:66};const purchase=cosmeticPurchase({coins:100,cost:25});assert.deepEqual(real,{readiness:72,mastery:66});assert.deepEqual(purchase,{coins:75,owned:true,purchased:true})});
test('developer activation requires five taps and exact code',()=>{assert.equal(fiveTapUnlocked(4),false);assert.equal(fiveTapUnlocked(5),true);assert.equal(developerCodeValid('JAKE-SECPLUS-TEST'),true);assert.equal(developerCodeValid('wrong'),false)});
test('reduced-motion disables nonessential animation',()=>{const css=fs.readFileSync(new URL('../src/styles.css',import.meta.url),'utf8');assert.equal(reducedMotionCss(css),true)});
test('correct feedback excludes incorrect-only wording',()=>{const s=app();assert.match(s,/Correct, but low confidence/);assert.match(s,/Why each other option is wrong/);assert.match(s,/Why your selected answer was tempting/);assert.match(s,/Targeted remediation/)});
test('question status is hidden outside developer mode',()=>{const s=app();assert.match(s,/state\.testMode\.enabled\?`<span class="quality/)});
test('boss UI and developer lab are present',()=>{const s=app();for(const term of ['Boss health','Learner shield','Developer Lab','Cosmetics','version-tap','Start targeted review'])assert.match(s,new RegExp(term))});
